SELECT --DISTINCT
1 as cd_ogn,
DT_REF, --DT_MVTC = DT_REF
CD_ABTR_LIM_NOVO, --CD_RAS_2022,
sum(VL_SDO_CTB) as VL_SDO_CTB,
sum(VL_PVS_CLCD_CTB) as VL_PVS_CLCD_CTB,
sum(VL_EXPO_ABGT) as VL_EXPO_ABGT, --VL_EXPO_ALT = VL_EXPO_ABGT
sum(VL_EXPO_PDRD_RSCO) as VL_EXPO_PDRD_RSCO, --VL_EXPO_PDRD_RSCO_ALT = VL_EXPO_PDRD_RSCO
sum(VL_PCL_PDRD_RSCO) as VL_PCL_PDRD_RSCO --VL_PCL_PDRD_RSCO_ALT = VL_PCL_PDRD_RSCO
FROM hive_d4q.cptl_rglo_msl
WHERE CD_IDFR_RBC_VLDO = 0 --IDFR_RBC_CTB_VLDO = CD_IDFR_RBC_VLDO
--AND dt_ref = '2021-12-31'
AND CD_QLF_TIP_OPR = 1
GROUP BY DT_REF, CD_ABTR_LIM_NOVO --, CD_RAS_2022