package coletorjava.parse.callback;

import coletorjava.parse.callback.basico.CotacaoProcessadaOpcaoResultadoDetalheCallbackHtmlBase;

public class CotacaoProcessadaOpcaoResultadoDetalheCallbackHtml extends CotacaoProcessadaOpcaoResultadoDetalheCallbackHtmlBase{



}